#!/bin/sh

SWAP_FILE=/swapfile

if [ ! -f $SWAP_FILE ]; then
	sudo fallocate -l 16G $SWAP_FILE
	sudo mkswap $SWAP_FILE
	sudo chmod 600 $SWAP_FILE
fi

sudo swapon $SWAP_FILE

sudo nix-env -p /nix/var/nix/profiles/system --delete-generations +1
sudo nix-collect-garbage -d 
sudo nixos-rebuild -j 1 switch # --upgrade

sudo swapoff $SWAP_FILE

