esphome:
  name: moroomwardrobe
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "NotANetwork"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Moroomwardrobe Fallback Hotspot"
    password: "VynwNZN3glml"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  
switch:
  - platform: gpio
    name: "Wardrobe light"
    pin: 14
