esphome:
    name: moroomwardrobe
    platform: ESP8266
    board: d1_mini

wifi:
    ssid: "NotANetwork"
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Moroomwardrobe Fallback Hotspot"
        password: "VynwNZN3glml"
    manual_ip:
        # Set this to the IP of the ESP
        static_ip: 192.168.0.11
        # Set this to the IP address of the router. Often ends with .1
        gateway: 192.168.0.1
        # The subnet of the network. 255.255.255.0 works for most home networks.
        subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
    
switch:
    - platform: gpio
      name: "Wardrobe light"
      pin: 14
    - platform: gpio
      name: "Wardrobe plant pump"
      pin: 5  # D1
      id: wardrobe_pump

sensor:
    - platform: dht
      model: DHT22
      pin: 13
      temperature:
          name: "Living Room Temperature"
      humidity:
          name: "Living Room Humidity"
      update_interval: 15s

# time:
#   - platform: sntp
#     on_time:
#       - seconds: 0
#         minutes: 11
#         hours: 10,13,16,18
#         then:
#           - switch.turn_on: wardrobe_pump

#       - seconds: 0
#         minutes: 12
#         hours: 10,13,16,19
#         then:
#           - switch.turn_off: wardrobe_pump
# time:
# - platform: sntp
# timezone: Etc/GMT
# on_time:
# - seconds: 0-20
# minutes: 15
# hours: '*'
# then:
# - switch.turn_on: wardrobe_pump
