esphome:
  name: mowater
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "NotANetwork"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mowater Fallback Hotspot"
    password: "VynwNZN3glml"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.171
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Water pump"
    pin: 14  # D5
    id: pump

# Example configuration entry
binary_sensor:
  - platform: gpio
    pin: 
      number: D2
      inverted: true
    name: "Outdoor noise"
    device_class: sound
    filters: 
      - delayed_off: 100s
      - delayed_on: 120ms

sensor:
  - platform: dht
    model: DHT22
    pin: 5
    temperature:
      name: "Balcony Temperature"
    humidity:
      name: "Balcony Humidity"
    update_interval: 15s
      #- platform: adc
      #pin: A0
      #name: "Outdoor noise"
      #update_interval: 1s
      #filters:
      #- exponential_moving_average:
      #alpha: 0.1
      #send_every: 5
