# Actually, although I have a pump here, this module is primarily used for MHZ-19 CO2 sensing
esphome:
  name: mhz19
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Monet"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mowater Fallback Hotspot"
    password: "VynwNZN3glml"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.14
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

uart:  # for MH-Z19
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

i2c:  # For light sensor
  sda: GPIO4
  scl: GPIO5
  scan: true

captive_portal:

# Enable logging
logger:
  baud_rate: 0  # Disables UART logging

# Enable Home Assistant API
api:
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: mhz19_id

ota:

switch:
  - platform: gpio
    name: "Water pump"
    pin: 14  # D5
    id: pump

# Example configuration entry
# binary_sensor:
#   - platform: gpio
#     pin: 
#       number: D2
#       inverted: true
#     name: "Outdoor noise"
#     device_class: sound
#     filters: 
#     # - delayed_off: 15s
#     # - delayed_on: 200ms
#       - delayed_off: 100s
#       - delayed_on: 120ms

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO0
    temperature:
      name: "Balcony Temperature"
    humidity:
      name: "Balcony Humidity"
    update_interval: 15s
      #- platform: adc
      #pin: A0
      #name: "Outdoor noise"
      #update_interval: 1s
      #filters:
      #- exponential_moving_average:
      #alpha: 0.1
      #send_every: 5
  - platform: mhz19
    id: mhz19_id
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: tsl2561
    name: "TSL2561 Ambient Light"
    address: 0x39
    update_interval: 60s
